### ISSUE TITLE
按照安装步骤运行会出错

### ISSUE THREAD

**Issue by njumzs** [jysperm/hexo-theme-simpleblock#8]
你好，我的simpleblock会报错

```
ERROR Process failed: layout/index.jade
TypeError: Cannot read property 'compile' of undefined
  at [object Object].View._precompile (/root/blog/node_modules/hexo/lib/theme/view.js:104:22)
  at [object Object].View (/root/blog/node_modules/hexo/lib/theme/view.js:13:8)
  at new Theme._View.View (/root/blog/node_modules/hexo/lib/theme/index.js:37:10)
  at Theme.setView (/root/blog/node_modules/hexo/lib/theme/index.js:71:20)
  at /root/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
  at tryCatcher (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
  at Promise._settlePromise (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
  at Promise._settlePromise0 (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
  at Promise._settlePromises (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
  at Promise._fulfill (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:629:18)
  at Promise._resolveCallback (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:424:57)
  at Promise._settlePromiseFromHandler (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:515:17)
  at Promise._settlePromise (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
  at Promise._settlePromise0 (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
  at Promise._settlePromises (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
  at Promise._fulfill (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:629:18)
  at /root/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
  at /root/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
  at fs.js:268:14
  at /root/blog/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
  at /root/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
  at /root/blog/node_modules/hexo/node_modules/warehouse/node_modules/graceful-fs/graceful-fs.js:43:10
  at /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
  at Object.oncomplete (fs.js:107:15)
```

当我浏览器输入url访问时,
hexo log显示为:
WARN  No layout: index.html
请问其他人没有遇到这个问题吗？

**Comment by jysperm** [comment]
请问在安装主题时是否运行了 npm install hexo-renderer-jade ？simpleblock 的模板是用 jade 编写的，需要依赖于这个插件。

**Comment by jysperm** [comment]
经过我的测试，确实在 Hexo 3.2 下 hexo-renderer-jade 没有被正确地加载，我试着将它加入到 package.json 中就可以加载了，不太清楚原因，官方的 Release Note 上有提到插件加载方式有变化，但没具体介绍和 package.json 的关系。你可以重新运行一遍 npm install hexo-renderer-jade --save 来将这个依赖加入 package.json

**Comment by njumzs** [comment]
恩，加--save就可以了，谢谢热情的回复
